const membersData = [
	{
		name: "Vlad Meșa",
		class: 2027,
		classIndex: "",
		birth: new Date(2007, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Vlad.jpg",
		thumbnailImage: "static/photo/Vlad.jpg",
		passions: "",
		roles: [1],
		description: "",
	},
	{
		name: "Robert Silea",
		class: 2027,
		classIndex: "A",
		birth: new Date(2007, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Robi.JPG",
		thumbnailImage: "static/photo/Robi.JPG",
		passions: "",
		roles: [1],
		description: "",
	},
	{
		name: "David Răileanu",
		class: 2028,
		classIndex: "B",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/David.jpg",
		thumbnailImage: "static/photo/David.jpg",
		passions: "",
		roles: [1],
		description: "",
	},
	{
		name: "Radu Stoica",
		class: 2028,
		classIndex: "B",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Radu.jpg",
		thumbnailImage: "static/photo/Radu.jpg",
		passions: "",
		roles: [1],
		description: "",
	},
	{
		name: "Ana Bătătorescu",
		class: 2029,
		classIndex: "A",
		birth: new Date(2010, 1, 15, 0, 0) * 1,
		descriptionImage: "static/photo/Ana.jpg",
		thumbnailImage: "static/photo/Ana.jpg",
		passions: "",
		roles: [1],
		description: "",
	},
	{
		name: "Anne Stavarache",
		class: 2029,
		classIndex: "A",
		birth: new Date(2009, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Anne.JPG",
		thumbnailImage: "static/photo/Anne.JPG",
		passions: "",
		roles: [1],
		description: "",
	},
	{
		name: "Daria Lazăr",
		class: 2027,
		classIndex: "A",
		birth: new Date(2007, 1, 15, 0, 0) * 1,
		descriptionImage: "static/photo/Daria.jpg",
		thumbnailImage: "static/photo/Daria.jpg",
		passions: "",
		roles: [0],
		description: "",
	},
	{
		name: "Teodora Stoica",
		class: 2028,
		classIndex: "A",
		birth: new Date(2008, 12, 4, 0, 0) * 1,
		descriptionImage: "static/photo/Tea.jpg",
		thumbnailImage: "static/photo/Tea.jpg",
		passions: "",
		roles: [0],
		description: "",
	},
	{
		name: "Alexandru Colojoară",
		class: 2029,
		classIndex: "A",
		birth: new Date(2009, 1, 15, 0, 0) * 1,
		descriptionImage: "static/photo/Alex.jpg",
		thumbnailImage: "static/photo/Alex.jpg",
		passions: "",
		roles: [0],
		description: "",
	},
	{
		name: "Alexa Șerban",
		class: 2026,
		classIndex: "E",
		birth: new Date(2006, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Alexa.JPG",
		thumbnailImage: "static/photo/Alexa.JPG",
		passions: "",
		roles: [2],
		description: "",
	},
	{
		name: "Amalia Călugăru",
		class: 2028,
		classIndex: "D",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Ami.jpg",
		thumbnailImage: "static/photo/Ami.jpg",
		passions: "",
		roles: [2],
		description: "",
	},
	{
		name: "Rareș Alexandru",
		class: 2029,
		classIndex: "A",
		birth: new Date(2009, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Rares.jpg",
		thumbnailImage: "static/photo/Rares.jpg",
		passions: "",
		roles: [2],
		description: "",
	},
	{
		name: "Rebecca Cojocaru",
		class: 2028,
		classIndex: "F",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Rebe.JPG",
		thumbnailImage: "static/photo/Rebe.JPG",
		passions: "",
		roles: [2],
		description: "",
	},
	{
		name: "Daiana Dodan",
		class: 2028,
		classIndex: "F",
		birth: new Date(2008, 10, 2, 0, 0) * 1,
		descriptionImage: "static/photo/Daiana.JPG",
		thumbnailImage: "static/photo/Daiana.JPG",
		passions: "",
		roles: [2],
		description: "",
	},
]
